server:
  port: 9002




client:
  post:
    department: http://DEPARTMENT-SERVICE/department

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://cms-dev:8080/auth/realms/aakashk-realm
          jwk-set-uri: http://cms-dev:8080/auth/realms/aakashk-realm/protocol/openid-connect/certs
          client-id: user-service
          client-secret: e345a1a1-0331-4145-8e6c-2ec3fae88007

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://brilp0146.sst.stp:8761/eureka/
  instance:
    hostname: localhost

feign:
  client:
    config:
      default:
        requestInterceptors:
          - com.example.userservice.interceptors.OAuthFeignRequestInterceptor



