server:
  port: 9090

spring:
  application:
    name: api-gateway
  main:
    #web-application-type: reactive
    allow-bean-definition-overriding: true
  devtools:
    restart:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://cms-dev:8080/auth/realms/aakashk-realm
          jwk-set-uri: http://cms-dev:8080/auth/realms/aakashk-realm/protocol/openid-connect/certs
          client-id: spring-gateway-client
          client-secret: 37654452-5868-42db-abf7-e1c4f023ca24

#      client:
#        provider:
#          keycloak:
#            issuer-uri: http://cms-dev:8080/auth/realms/aakashk-realm
#        registration:
#          keycloak-spring-gateway-client:
#            provider: keycloak
#            client-id: spring-gateway-client
#            client-secret: 37654452-5868-42db-abf7-e1c4f023ca24
#            authorization-grant-type: authorization_code
#            redirect-uri: "http://brilp0146.sst.stp:9090/"
#            scope: openid

#  cloud:
#    gateway:
#      default-filters:
#        - TokenRelay
#      routes:
#        - id: userModules
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/users/**
#        - id: deparmentModules
#          uri: lb://DEPARTMENT-SERVICE
#          predicates:
#            - Path=/department/**






eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

#keycloak:
#  realm: microservice
#  auth-server-url: http://localhost:8090/auth
#  resource: api-gateway-client
#  public-client: true
#  bearer-only: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

