server:
  port: 9191

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  devtools:
    restart:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/auth/realms/microservice
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8090/auth/realms/microservice
        registration:
          keycloak-spring-gateway-client:
            provider: keycloak
            client-id: api-gateway-client
            client-secret: e3312665-bf66-4931-bddf-81dc9a96bbd2
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            scope: openid

  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: userModules
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: deparmentModules
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/department/**






eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

#keycloak:
#  realm: microservice
#  auth-server-url: http://localhost:8090/auth
#  resource: api-gateway-client
#  public-client: true
#  bearer-only: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

